<template functional>
	<section id="add-multiple" key="add-multiple">
		<h4>“Add Multiple” Button</h4>
		<p>Click the “Add Multiple” button, located next to the <a href="#card-adder">card adder</a> in the <a href="#list-editor">List Editor</a>, to go to the <a href="#card-list-entry">Card List Entry page</a>.</p>

		<section id="card-list-entry">
			<h5>Card List Entry Page</h5>
			<p>When you create a <a href="#start-new-deck">new deck</a>, you might already know many or all of the certain cards you’re going to include in it. Or, maybe you’ve copied the card list of a <i>Magic</i> deck from a source outside MTG Deck Builder, and you’d like to interact with that deck inside MTG Deck Builder.</p>
			<p>In either of those cases, you could build the deck with the <a href="#card-adder">card adder tool</a>, inserting each of the card names one by one. However, a faster way instead is to write a list of the known card names all together. You can do this on the Card List Entry page, accessible by clicking the <a href="#add-multiple">“Add Multiple” button</a> in the <a href="#list-editor">List Editor</a>.</p>
			<p>The Card List Entry page features a submission form. In the form, you can write a list of the names of <i>Magic: The Gathering</i> cards to put into your deck. Precede each name with a number for its <a href="#card-quantities">quantity</a> within your deck’s main <a href="#card-groups">card group</a>.</p>
			<p>The page provides you instructions on how to write a card list in the acceptable format. (This format is the same one used for card lists generated by the <a href="#text-renderer">Text Renderer</a>.) It’s important to follow that format exactly, or else the names in your list may fail to be added to your deck. For any single lines of your list that don’t match the acceptable list format, they’ll be ignored.</p>
			<p>The Card List Entry page can also be used for another purpose: to change the quantities of any card names that already exist in your deck’s main card group. Setting a name’s quantity to 0 will remove that name from the group.</p>
			<p>When you’re done, click the “Add Cards” button to submit your list in the form. You’ll then be shown an overview of the submission results. It tells you about every entry from your submitted list, and whether the app was able to get the card names from those entries—and, if not, with the reasons why.</p>
			<p>For each valid card name you submit, it’s added to the main card group of your deck.</p>
		</section>
	</section>
</template>
