<template>
	<div v-if="deckDataOutdated" class="wrap">
		<aside class="outdated-deck-data-notice wrap">
			<p>⚠ This deck is using an outdated set of card data. Update it to get enhanced app features!</p>
			<p
				v-if="!updatingDeckData"
				class="update-button-cont"
			>
				<button @click="allowDataUpdate()">Update</button>
			</p>
			<p
				v-else
				class="update-button-cont loading-indicator"
			>
				<em>Updating now&hellip;</em>
			</p>
		</aside>
	</div>
</template>

<script>
import requestScryfallData from '@/mixins/requestScryfallData.js'

export default {
	mixins: [requestScryfallData],
	data () {
		return {
			oldCardQty: 0,
			totalCardsUpdated: 0,
			updatingDeckData: false
		}
	},
	props: {
		deck: Object
	},
	computed: {
		combinedDeckTotals () {
			return this.deck.cards.length + this.deck.sideboard.cards.length
		},
		deckDataOutdated () {
			return this.deck.dataVersion < 99
		}
	},
	created () {
		this.determineDeckDataVersion()
	},
	methods: {
		/**
		 * Check whether any `card` object includes the `keywords` key (even if it's set to no value). Card objects generated by older versions of the app are missing the `keywords` key, as well as `power` and `toughness` keys simultaneously, and so certain parts of the app won't be able to work properly.
		 */
		determineDeckDataVersion () {
			const deck = this.deck

			if (!deck.dataVersion || this.deckDataOutdated) {
				const haveKeywordsObjectKey = () => {
					for (let i = 0; i < deck.cards.length; i++) {
						if (!deck.cards[i].keywords) {
							return 1
						}
					}
					return 2

					// No need to bother checking the sideboard's cards for the `keywords` object key, because the sideboard was released after `keywords`.
				}

				deck.dataVersion = haveKeywordsObjectKey()

				this.$nextTick(() => {
					this.$store.commit('setDecks', this.$store.state.decks)
				})
			}
		},
		allowDataUpdate () {
			if (this.combinedDeckTotals > 150) {
				alert('⚠ Sorry, this deck’s data cannot be updated because it has too many cards.')
			} else {
				console.clear()

				this.$store.commit('setShowSideboard', false)
				this.updateCardGroupData(this.deck)
				// this.updatingDeckData = true
			}
		},
		updateCardGroupData (group) {
			console.log('>> updateCardGroupData()')
			// console.log(`Updated (${
			// 	(totalCardsUpdated / combinedDeckTotals * 100).toFixed(0)
			// }%)`)

			const callback = () => {
				this.totalCardsUpdated++
				console.log(this.totalCardsUpdated)
			}

			for (let i = 0; i < group.cards.length; i++) {
				setTimeout(() => {
					this.oldCardQty = group.cards[i].qty

					this.requestScryfallData(group.cards[i].name, callback())
					// console.log(group.cards[i].name)
					// callback()

					if (this.totalCardsUpdated === this.deck.cards.length) { // Once all the cards in the main group have been updated...
						setTimeout(() => {
							this.$store.commit('setShowSideboard', true)
							this.updateCardGroupData(this.deck.sideboard)
						}, 101)
					} else if (this.totalCardsUpdated === this.combinedDeckTotals) { // Once all the cards in both the main and sideboard groups have been updated...
						setTimeout(() => {
							console.log('✅ Finished updating!')
							// this.$router.go(0) // Reload the page
						}, 500) // Add a little extra time to let the user's CPU work with the updated card values before reloading the page.
					}
				}, 100 * (i + 1))
			}
		}
	}
}
</script>

<style lang="scss">
	@import '@/sass/page-deck.scss';
</style>
