<template functional>
	<section id="add-card-list" key="add-card-list">
		<h4>Add Card List Button</h4>
		<p>When creating a <a href="#create-deck">new deck</a>, you might know many or all of the certain <i>Magic</i> cards that you plan to include in it. Though you can use the <a href="#card-adder">card adder</a> to add those card names to your deck one by one, a faster method is to use the submission form on the <a href="#card-list-entry">Card List Entry page</a> instead.</p>
		<p>To go to the Card List Entry page, click the Add Card List button, which is next to the card adder section in the <a href="#deck-editor">Deck Editor</a>.</p>

		<section id="card-list-entry">
			<h5>Card List Entry Page</h5>
			<p>You can access the Card List Entry page by clicking the <a href="#deck-editor">Deck Editor</a>’s <a href="#add-card-list">Add Card List</a> button.</p>
			<p>The Card List Entry page has a submission form in which you can enter text for multiple card names to add at once to your deck’s main <a href="#card-groups">card group</a>, along with assigning the quantity for each name.</p>
			<p>You can also use the submission form to change the quantities of any card names that already exist in your deck’s main card group. Setting a name’s quantity to 0 will remove that name from the main group.</p>
			<p>The Card List Entry page provides you instructions on how to write card lists as text in the correct format. (This format is the same one of card lists generated by the “<a href="#render-as-text-action">render as text</a>” deck action.) The list you enter must strictly follow that format, or else it’ll be rejected or cause errors in trying to add cards.</p>
			<p>Once you submit a card list, you’re automatically taken to the results page. It informs you about all the card names you’ve submitted that have been successfully added to your deck (if any), and other names that couldn’t be added (if any) with the reason why.</p>
			<p>The Card List Entry page is especially helpful if you’ve got a <i>Magic</i> deck’s card list in the form of plain text from a source outside MTG Deck Builder, and you want to interact with that deck inside MTG Deck Builder. However, importing a <a href="#deck-data-files">deck data file</a>, if available, is generally better for sharing a deck between computers or mobile devices all using MTG Deck Builder, because the data files contain additional deck information that’s missing from plain text card lists.</p>
		</section>
	</section>
</template>
