<template functional>
	<section id="add-card-list" key="add-card-list">
		<h4>Add Card List Button</h4>
		<p>When creating a <a href="#create-deck">new deck</a>, you might know several or all of the certain cards that you plan to include in it. Though you could use the <a href="#card-adder">card adder</a> to add each card name one by one, a faster method is to use the <a href="#card-list-entry">Card List Entry</a> submission form instead.</p>
		<p>To go to the Card List Entry page, click the “Add Card List” button in the <a href="#deck-editor">Deck Editor</a>, positioned next to the card adder section.</p>

		<section id="card-list-entry">
			<h5>Card List Entry Page</h5>
			<p>In the submission form of the Card List Entry page, you can enter text for multiple card names to add at once to your deck’s main <a href="#card-groups">card group</a>, along with assigning the quantity for each name.</p>
			<p>You can also use the submission form to change the quantities of any card names that already exist in your deck’s main card group. Setting a quantity to 0 will remove that name from the main card group.</p>
			<p>The Card List Entry page provides instructions on how to write card lists as text in the correct format. (This format is the same one for card lists generated by the <a href="#convert-to-text-action">Convert to Text</a> deck action.) Your entered list must follow that format or else your list will probably be rejected or cause errors in trying to add the cards.</p>
			<p>After you submit a card list, you’re taken to the results page, which tells you which submitted card names have been successfully added to your deck (if any), and which other names could not be added (if any) with the reason why.</p>
		</section>
	</section>
</template>
