<template functional>
	<section id="add-multiple" key="add-multiple">
		<h4>“Add Multiple” Button</h4>
		<p>Click the “Add multiple” button, located next to the <a href="#card-adder">card adder</a> in the <a href="#list-editor">List Editor</a>, to go to the <a href="#card-list-entry">Card List Entry page</a>.</p>

		<section id="card-list-entry">
			<h5>Card List Entry Page</h5>
			<p>When you create a <a href="#create-deck">new deck</a>, you might already know many or all of the certain cards you’re going to include in it. Or, maybe you’ve copied the card list for a <i>Magic</i> deck from a source outside MTG Deck Builder, and you’d like to interact with that deck inside MTG Deck Builder.</p>
			<p>In either of those cases, you could build the deck with the <a href="#card-adder">card adder tool</a>, inserting each of the card names one by one. However, a faster way is to instead submit a list of card names together. To do that, first click the <a href="#add-multiple">“Add multiple” button</a> in the <a href="#list-editor">List Editor</a>, which takes you to the Card List Entry page.</p>
			<p>The Card List Entry page features a submission form, where you can write a list of multiple names of <i>Magic</i> cards, along with assigning the quantity to each name. When you’re done, click the “Add Cards” button to submit the form, which adds those submitted cards to the main <a href="#card-groups">card group</a> of your deck.</p>
			<p>You could also use this submission form to edit the quantities of any card names that already exist in your deck’s main card group. Setting a name’s quantity to 0 will remove that name from the main card group.</p>
			<p>The Card List Entry page provides you instructions on how to write a card list in the accepted list format. (This format is the same one used for card lists generated by the <a href="#text-renderer">Text Renderer</a>.) It’s important you exactly follow that format, or else the card names in your list may fail to be added to your deck. The app ignores any single lines of your list that don’t match the accepted format.</p>
			<p>Once you submit a list, you’ll then be shown an overview of the submission results. It tells you about every entry from your submitted list, and whether the entries have successfully added the cards to your deck—and, if not, with the reasons why.</p>
		</section>
	</section>
</template>
