<template functional>
	<section id="add-multiple" key="add-multiple">
		<h4>“Add Multiple” Button</h4>
		<p>When you create a <a href="#create-deck">new deck</a>, you might already know many or all of the certain <i>Magic</i> cards you’re going to include in it. Or, maybe you have the plain-text card list of a deck from a source outside MTG Deck Builder, and you’d like to interact with that deck inside MTG Deck Builder.</p>
		<p>You could add each of those known card names to your deck one by one using the <a href="#card-adder">card adder</a> tool. However, a faster way is to use the submission form on the <a href="#card-list-entry">Card List Entry page</a> instead.</p>
		<p>To go to the Card List Entry page, click the “Add multiple” button, located next to the card adder in the <a href="#list-editor">List Editor</a>.</p>

		<section id="card-list-entry">
			<h5>Card List Entry Page</h5>
			<p>You can access the Card List Entry page by clicking the <a href="#add-multiple">“Add multiple” button</a> in the <a href="#list-editor">List Editor</a>.</p>
			<p>The Card List Entry page has a submission form in which you can enter text for multiple names of <i>Magic</i> cards to add at once to your deck’s main <a href="#card-groups">card group</a>, along with assigning the quantity to each name.</p>
			<p>You can also use the submission form to change the quantities of any card names that already exist in your deck’s main card group. Setting a name’s quantity to 0 will remove that name from the main group.</p>
			<p>The Card List Entry page provides you instructions on how to write card lists in the correct format. (This format is the same one used for card lists generated by MTG Deck Builder’s “<a href="#render-as-text-action">render as text</a>” action.) It’s important that the list you enter follows the format, because otherwise, some or all of your list will be rejected or cause errors in trying to add the cards.</p>
			<p>Once you submit a card list, you’re automatically taken to the results page. It informs you about all the card names you’ve submitted that have been successfully added to your deck (if any), and other names that couldn’t be added (if any) with the reason why.</p>
		</section>
	</section>
</template>
