<template functional>
	<section id="add-multiple" key="add-multiple">
		<h4>“Add Multiple” Button</h4>
		<p>The “Add multiple” button is a button located next to the <a href="#card-adder">card adder</a> in the <a href="#list-editor">List Editor</a>. Click it to go to the <a href="#card-list-entry">Card List Entry page</a>.</p>

		<section id="card-list-entry">
			<h5>Card List Entry Page</h5>
			<p>When you create a <a href="#create-deck">new deck</a>, you might already know many or all of the certain cards you’re going to include in it. Or, maybe you found the plain-text card list of a <i>Magic</i> deck from somewhere other than MTG Deck Builder, and you’d like to interact with that deck inside MTG Deck Builder.</p>
			<p>In either of those cases, you could build the deck by adding each of the known card names to it one by one using the <a href="#list-editor">List Editor</a>’s <a href="#card-adder">card adder</a> tool. However, a faster way is to go to the Card List Entry page instead, which you can do by clicking the <a href="#add-multiple">“Add multiple” button</a> in the List Editor.</p>
			<p>The Card List Entry page features a submission form. In this form, you can write multiple names of <i>Magic</i> cards to add all at once to your deck’s main <a href="#card-groups">card group</a>, along with assigning the quantity to each name.</p>
			<p>You can also use the submission form to edit the quantities of any card names that already exist in your deck’s main card group. Setting a name’s quantity to 0 will remove that name from the main group.</p>
			<p>The Card List Entry page provides you instructions on how to write card lists in the correct list format. (This format is the same one used for card lists generated by MTG Deck Builder’s “<a href="#render-as-text-action">render as text</a>” action.) It’s important that the list you enter follows that format exactly, or else your list may be rejected or cause errors in trying to add the cards.</p>
			<p>After submitting a list from the Card List Entry page, you’ll be shown the results page. It’ll tell you about every card name you’ve submitted and whether it was successfully added to your deck or not, and, if not, with the reason why.</p>
		</section>
	</section>
</template>
